-- No-op migration.
--
-- This file was originally generated as a remote-schema catch-up for the
-- 20251227120000 order tracking changes. Those changes are now represented by
-- 20251227120000_add_order_email_tracking.sql, so this version is kept only to
-- preserve migration history for environments that already recorded it.
